name: Add Configuration
description: Request a new configuration key and value to be added
title: "[ADD CONFIG] "

body:
  - type: input
    id: application
    attributes:
      label: Application Name
      description: Enter the target application
      placeholder: LMS
    validations:
      required: true

  - type: input
    id: key
    attributes:
      label: Configuration Key
      description: Enter the new configuration key
      placeholder: NEW_FEATURE_ENABLED
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: Configuration Value
      description: Enter the value for the new configuration
      placeholder: true
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Change Reason
      description: Explain why this configuration is required
      placeholder: Enable new feature rollout
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have reviewed the request before submission.
          required: true