name: Application Promotion
description: Promote application to next environment
title: "[PROMOTION] "

body:

  - type: input
    id: application
    attributes:
      label: Application Name
    validations:
      required: true

  - type: input
    id: current
    attributes:
      label: Current Environment
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target Environment
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Change Reason
    validations:
      required: true