name: Configuration Change Request
description: Submit a configuration change request
title: "[CONFIG CHANGE] "

body:
  - type: input
    id: application
    attributes:
      label: Application Name
      description: Enter the target application
      placeholder: LMS
    validations:
      required: true

  - type: input
    id: key
    attributes:
      label: Configuration Key
      description: Enter the configuration key to be updated
      placeholder: DB_HOST
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: New Value
      description: Enter the new configuration value
      placeholder: aws-prod-db.company.com
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Change Reason
      description: Explain why this change is required
      placeholder: Database migration to AWS
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have reviewed the change request before submission.
          required: true