name: Configuration Change Request
description: Submit a configuration change request
title: "[CONFIG CHANGE] "

body:

  - type: input
    id: application
    attributes:
      label: Application Name
      placeholder: RECON
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Section Name
      placeholder: shared_tokens
    validations:
      required: true

  - type: input
    id: key
    attributes:
      label: Configuration Key
      placeholder: PortalEnvironment
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: New Value
      placeholder: DR
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Change Reason
      placeholder: Disaster Recovery Testing
    validations:
      required: true