name: Configuration Pipeline

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: write

jobs:

  dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: DEV Validation
      run: |
        echo "===== ISSUE BODY START ====="
        echo "${{ github.event.issue.body }}"
        echo "===== ISSUE BODY END ====="

        echo ""
        echo "Checking JSON file..."
        cat config/configurations.json

        echo ""
        echo "DEV Debug Complete"


  qa:
    needs: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: QA Validation
        run: |
          echo "Running QA Validation"

          if grep -q '"DB_HOST"' config/configurations.json; then
            echo "✓ Configuration Key Found"
          else
            echo "✗ Configuration Key Missing"
            exit 1
          fi

  uat:
    needs: qa
    runs-on: ubuntu-latest

    steps:
      - name: UAT Validation
        run: |
          echo "Running UAT Validation"

          echo "✓ Business Validation Passed"
          echo "✓ Change Review Completed"

  prod:
    needs: uat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: PROD Validation
        run: |
          echo "Running PROD Validation"

          echo "✓ DEV Passed"
          echo "✓ QA Passed"
          echo "✓ UAT Passed"

          echo ""
          echo "DEPLOYMENT PIPELINE"
          echo "DEV -> QA -> UAT -> PROD"

          echo ""
          echo "✓ Ready For Deployment"

      - name: Run Configuration Processing Engine
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          node engine/process-request.js

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "Update configuration" || echo "No changes"

          git push