name: Test Config Repo Access

on:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: sugaredcookie
            repositories: linedata-config-store

      - name: Checkout Config Repo
        uses: actions/checkout@v4
        with:
          repository: sugaredcookie/linedata-config-store
          token: ${{ steps.app-token.outputs.token }}
          path: config-repo

      - name: Show Workflow Repo Files
        run: |
          echo "===== WORKFLOW REPO ====="
          ls -R scripts
          ls -R engine

      - name: Show Config Repo Files
        run: |
          echo "===== CONFIG REPO ====="
          ls -R config-repo

      - name: Update Config
        run: |
          node scripts/test-json-update.js

      - name: Verify Change
        run: |
          echo "===== UPDATED FILE ====="
          cat config-repo/configs/RECON/shared_tokens.json

      - name: Commit Changes
        run: |
          cd config-repo

          git config user.name "Config Bot"
          git config user.email "bot@demo.com"

          git add .

          git commit -m "Update PortalEnvironment to DR" || echo "No changes"

      - name: Debug Remote
        run: |
            cd config-repo
            git remote -v

      - name: Push Changes
        env:
            TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
            cd config-repo

            git remote set-url origin \
            https://x-access-token:${TOKEN}@github.com/sugaredcookie/linedata-config-store.git

            git push